### ISSUE TITLE
Inconsistent mapping of scala.collection.Map to Avro `map` type

### ISSUE THREAD

**Issue by saniyatech** [sksamuel/avro4s#118]
We have few case classes with scala.collection.Maps. Generating Avro schema for the case classes and trying to serialize data to Avro, I hit this issue with Avro4s.

I have generated sample classes based off my code and I am able to reproduce the issue:

The following is a case class which includes scala.collection.Map[String, Int]. This is supported by Avro!

// TestCase.scala:
```
package my.test

import scala.collection.Map
case class TestCase(
                     id: String,
                     count: Long,
                     firstMap: Map[String, Int],
                     secondMap: Map[String, Int]
                   )
```

The spec for the TestCase class to produce the issue:
// TestCaseSpec.scala:
```
package my.test

import com.sksamuel.avro4s._
import org.scalatest.FlatSpec

class TestCaseSpec extends FlatSpec {

  "TestCase" should "generate schema" in {
    val schema = AvroSchema[TestCase]
    println(schema.toString(true))
  }

}
```

The following is the output from executing the spec, which is basically printing the Avro schema. Notice the firstMap and the secondMap have not been converted to Avro `map` type, rather the firstMap is converted to record of 'Map' while the secondMap is converted to type 'scala.collection.Map'. Serializing data from the case class to Avro format also fails!
```
{
  "type" : "record",
  "name" : "TestCase",
  "namespace" : "my.test",
  "fields" : [ {
    "name" : "id",
    "type" : "string"
  }, {
    "name" : "count",
    "type" : "long"
  }, {
    "name" : "firstMap",
    "type" : {
      "type" : "record",
      "name" : "Map",
      "namespace" : "scala.collection",
      "fields" : [ ]
    }
  }, {
    "name" : "secondMap",
    "type" : "scala.collection.Map"
  } ]
}
```

**Comment by NetanelRabinowitz** [comment]
Yes the only supported map is scala.collection.immutable.Map which is the one aliasing from Predef. for current version you can use it (get rid of the collection.Map import) or supply a [custom type mapping](https://github.com/sksamuel/avro4s#custom-type-mappings). 

I trie'd to replace the type class instance from predef Map to the collection.Map trait because both mutable and immutable extends it, but that didn't work well for the mutable version If I remember correctly. when I add another type class instance for each type every thing work as expected.
@sksamuel do you know of any elegant way we can support collection.Map, mutable and immutable version of collection? or adding each version explicitly is the way to go ?

**Comment by saniyatech** [comment]
Netanel: Thanks for looking into this issue!

We are using this library for an Apache Spark application. There is a limitation in Spark that you have to use `scala.collection.Map` for Maps. While the limitation with Avro4s requires usage of `scala.predef.Map`.  I ended up creating custom type mapping for `scala.collection.Map`. So I am going to close the ticket.
