### ISSUE TITLE
Special Character throwing errors

### ISSUE THREAD

**Issue by dileepprasad-developer** [sksamuel/avro4s#119]
Hi,
I found your library really useful and a life saver. But having issues while working with special characters. The API breaks and throws apache.avro.SchemaParseException: Illegal character  while hiving "-" in the key field of the JSON. I tried to escape the special characters , but the code breaks at 
case JObject(values) =>

def convert(name: String, value: JValue): Schema = try {
   value match {
      case JArray(value) => Schema.createArray(convert(name, value.head))
      case JBool(_) => Schema.create(Schema.Type.BOOLEAN)
      case JDecimal(_) => Schema.create(Schema.Type.DOUBLE)
      case JDouble(_) => Schema.create(Schema.Type.DOUBLE)
      case JInt(_) => Schema.create(Schema.Type.LONG)
      case JLong(_) => Schema.create(Schema.Type.LONG)
      case JNothing => Schema.create(Schema.Type.NULL)
      case JNull => Schema.createUnion(util.Arrays.asList(Schema.create(Schema.Type.NULL), createStringSchema))
      case JString(_) => createStringSchema
      case JSet(value) => Schema.createArray(convert(name, value.head))
      case JObject(values) =>

Is there a way to work with special characters which could break scala variable naming conventions?
Thanks,
Dileep.

**Comment by NetanelRabinowitz** [comment]
Actually the non ascii characters restriction is comes from Avro.  so currently you can't do much about it.
The only reasonable thing we can do is to transform the json key's into ascii characters (camelCase instead of snakeCase or lispCase) and create a bit different schema. If you than want to turn that case class back to the original json you will need to write it using the original name strategy.
