### ISSUE TITLE
How can I use this to generate the avro schema for a JSON payload?

### ISSUE THREAD

**Issue by tikaa** [sksamuel/avro4s#13]
$subject please.

Regards
Awanthika

**Comment by sksamuel** [comment]
Just to clarify, you have a json document and you want to generate a schema
from that?

**Comment by tikaa** [comment]
Thanks for the reply!

Yes,

I have a json Payload,

Im under the impression that I first need to generate the JSON schema for
this and then generate the avro schema from the json Schema

is this the case?

or else how can I generate the avro schema for the json payload I have.


Regards
Awanthika

Awanthika Senarath
Software Engineer, WSO2 Inc.
Mobile: +94717681791

**Comment by sksamuel** [comment]
One of the issues going from json to avro is that you don't necessarily have all the information you need. For example

{
  foo: 3
}

Is that an Int or a Double that happens to have an int value. Or even worse with nulls because then you don't know what to use at all. But if that's ok, add avro4s-json to your classpath and then take a look at the JsonToAvroConverter class.

**Comment by tikaa** [comment]
Thanks Stephen,

Going through Json schema I figured out some limitations. I will test and
figure out whether those limitations affect our work.

Thanks for the information.

Regards
Awanthika

Awanthika Senarath
Software Engineer, WSO2 Inc.
Mobile: +94717681791
