### ISSUE TITLE
FromValue / ToValue serializability

### ISSUE THREAD

**Issue by ckchow** [sksamuel/avro4s#223]
Is it feasible to make FromValue and ToValue serializable?

**Comment by Zhen-hao** [comment]
I encountered the same problem. 
It seems that making ToRecord and FromRecord serializable is not enough. Because the SchemaFor macro can pull in non-serializable objects. 
For that reason, I find it very hard to use this library in Spark and Flink.  

It also relates to https://github.com/sksamuel/avro4s/issues/19#issuecomment-385678804

**Comment by sksamuel** [comment]
In the 2.0 development branch the equivalent classes (Encoder and Decoder, might be renamed yet) are serializable.

**Comment by sksamuel** [comment]
If you want to try 2.0.0-M3, all the required traits are now serializable.

**Comment by sksamuel** [comment]
2.0.0 is now released, so closing this ticket.
