### ISSUE TITLE
How to generate SchemaFor at runtime?

### ISSUE THREAD

**Issue by zygm0nt** [sksamuel/avro4s#308]
Hi
I've been wondering if it's possible to run SchemaFor implicits generation at runtime.

I'd like to have the following behavior:

```
object GenerateSchema {

  def apply[T <: Product](sourceClass: Class[T], outputDirectory: String): Unit = {
    implicit val schemaFor = SchemaFor.applyMacro[T]
    val schemaLocation = SchemaCompiler.schemaCompiler.compileClass(sourceClass, outputDirectory)
    println(s"Saved schema to: $schemaLocation")
  }
}


object RunGenerateSchema extends App {

  GenerateSchema(classOf[TimestampedItem], "/tmp/some_output")
}
```

This does not work currently because of internal check in avro4s:

```
Error:(9, 30) GenerateSchema.T is not a case class: This macro is only designed to handle case classes
    implicit val schemaFor = SchemaFor.applyMacro[T]
```

I don't know if macros can be used in this manner.

**Comment by klass-ivan** [comment]
I don't think it's possible with macros - they're applied at compile time.
I assume the `sourceClass` argument goes there from reflections result - (Otherwise you can just use implicit SchemaFor[T] and a `ClassTag[T]` instead of arguments, so it will look like `generateSchema[TimestampedItem]("/tmp/some_output")` and you've it  at compile time)

Having a similar problem, we come to 2-step solution: 
 - A simple app that lists all classes we need and writes a generated scala-code
 - Compile & run that generated code, providing an argument where to store schema files

Here is a snippet for code generation:
```
/** Represents an entry to generate *.avsc
  * The `typeName` is needed explicitly because enums and singleton classes may have "$" in java runtime,
  * but we need its name in scala code
  */
case class AvscFor(cls: Class[_], typeName: String, targetFileName: String)


val replaceBlock = "<<<code>>>"
val methodName   = "avsc"

val codeGenTemplate =
    s"""
    |package foo.bar
    |
    |import com.sksamuel.avro4s.SchemaFor
    |import java.io.File
    |import java.nio.file.{Files, Paths}
    |
    |object GenerateAvsc extends App with foo.bar.SchemaForCustomization {
    |
    |  def writeSchemas(targetDir: String): Unit = {
    |    def $methodName[T](name: String)(implicit schemaFor: SchemaFor[T]): Unit = {
    |      val pathParts = name.split('/')
    |      Files.createDirectories(
    |        Paths.get(targetDir, pathParts.init: _*)
    |      )
    |      Files.write(
    |        Files.createFile(Paths.get(targetDir, pathParts: _*)),
    |        schemaFor.schema.toString(true).getBytes("UTF-8")
    |      )
    |    }
    |    $replaceBlock
    |  }
    |
    |  args match {
    |    case Array(targetDir) => {
    |      val dirFile = new File(targetDir)
    |      require(dirFile.isDirectory, s"$$dirFile is not a directory!")
    |      writeSchemas(targetDir)
    |    }
    |  }
    |}
    """.stripMargin

val reflectionClasses: List[Class[_]] = ???

val schemasToWrite: List[AvscFor] = reflectionClasses.map(c => ???)

def codeGen(classNames: List[String], scalaSourceFileOut: String): Unit = {
  val content = codeGenTemplate.replace(
    replaceBlock,
    schemasToWrite
      .map(t => s"""$methodName[${t.typeName}]("${t.targetFileName}")""")
      .mkString(
        "\n    "
      )
  )
  Files.write(
    Paths.get(scalaSourceFileOut),
    content.getBytes("UTF-8")
  )
}

```
which results in something like:

package foo.bar

import com.sksamuel.avro4s.SchemaFor
import java.io.File
import java.nio.file.{Files, Paths}

object GenerateAvsc extends App with invitae.data.schema.AvroSchemaDerivation {

  def writeSchemas(targetDir: String): Unit = {
    def avsc[T](name: String)(implicit schemaFor: SchemaFor[T]): Unit = {
      val pathParts = name.split('/')
      Files.createDirectories(
        Paths.get(targetDir, pathParts.init: _*)
      )
      Files.write(
        Files.createFile(Paths.get(targetDir, pathParts: _*)),
        schemaFor.schema.toString(true).getBytes("UTF-8")
      )
    }

    avsc[foo.schema.bar.Baz]("foo/schema/bar/Baz.avsc")
    avsc[foo.schema.bar.BooEnum.Value]("foo/schema/bar/BooEnum.avsc")
  }

  args match {
    case Array(targetDir) => {
      val dirFile = new File(targetDir)
      require(dirFile.isDirectory, s"$dirFile is not a directory!")
      writeSchemas(targetDir)
    }
  }
}

**Comment by zygm0nt** [comment]
Thanks for this extensive writeup. Nice solution. I'll try to use this in my case. Thanks.
