### ISSUE TITLE
Deserialization seems failed

### ISSUE THREAD

**Issue by pandaforme** [sksamuel/avro4s#35]
```scala
object AvroExample extends App {
  val pepperoni = Pizza("pepperoni", Seq(Ingredient("pepperoni", 12, 4.4), Ingredient("onions", 1, 0.4)), false, false, 98)
  val hawaiian = Pizza("hawaiian", Seq(Ingredient("ham", 1.5, 5.6), Ingredient("pineapple", 5.2, 0.2)), false, false, 91)

  val os = AvroOutputStream[Pizza](new File("pizzas.avro"))
  os.write(pepperoni)
  os.close()

  val is = AvroInputStream[Pizza](new File("pizzas.avro"))
  println(is.iterator.toList)
  is.close()
}
```
I follow example and get a empty List.., it seems deserialization failed

**Comment by jeroentervoorde** [comment]
Hi,

The problem is that AvroOutputStream generates a file in .avro format (with header etc) and AvroInputStream expects a concatened series of serialized objects without the header.

I worked around this by creating a AvroDataReader. Setting binaryModeDisabled to false also works.

For example:

'''
import java.io.File

import com.sksamuel.avro4s._
import org.apache.avro.file.{DataFileReader, SeekableFileInput, SeekableInput}
import org.apache.avro.generic.{GenericDatumReader, GenericRecord}

object AvroExample extends App {
  case class Ingredient(name: String, sugar: Double, fat: Double)
  case class Pizza(name: String, ingredients: Seq[Ingredient], vegetarian: Boolean, vegan: Boolean, calories: Int)

  val pepperoni = Pizza("pepperoni", Seq(Ingredient("pepperoni", 12, 4.4), Ingredient("onions", 1, 0.4)), false, false, 98)
  val hawaiian = Pizza("hawaiian", Seq(Ingredient("ham", 1.5, 5.6), Ingredient("pineapple", 5.2, 0.2)), false, false, 91)

  val os = AvroOutputStream[Pizza](new File("pizzas.avro"), binaryModeDisabled = false)
  os.write(pepperoni)
  os.close()

  val is = AvroInputStream[Pizza](new File("pizzas.avro"))
  println(is.iterator.toList)
  is.close()

  val os2 = AvroOutputStream[Pizza](new File("pizzas2.avro"), binaryModeDisabled = true)
  os2.write(pepperoni)
  os2.close()

  val is2 = AvroDataReader[Pizza](new SeekableFileInput(new File("pizzas2.avro")))
  println(is2.iterator.toList)
  is2.close()
}

case class AvroDataReader[T](in: SeekableInput)(implicit schemaFor: SchemaFor[T], fromRecord: FromRecord[T]) {

  import scala.collection.JavaConversions._

  val datumReader = new GenericDatumReader[GenericRecord](schemaFor())
  val dataFileWriter = new DataFileReader[GenericRecord](in, datumReader)

  def iterator(): Iterator[T] = dataFileWriter.iterator().map(fromRecord.apply)

  def close(): Unit = {
    dataFileWriter.close()
    in.close()
  }
}
'''

**Comment by sksamuel** [comment]
As @jeroentervoorde says the issue is about whether the file is data or binary (has the schema or not). I don't think its very clear how it works at the moment, and there's inconsistencies. I'm going to deprecate the existing factory methods, and make new ones that make it explicit what you are doing. Then I'll release that as 1.5.0

**Comment by sksamuel** [comment]
So I've upgraded to avro 1.8.1 and at the same time changed the factory methods (others are deprecated and still there). So it's nice and clear now:

Data support:
```scala
   val pepperoni = Pizza("pepperoni", Seq(Ingredient("pepperoni", 12, 4.4), Ingredient("onions", 1, 0.4)), false, false, 98)
      val hawaiian = Pizza("hawaiian", Seq(Ingredient("ham", 1.5, 5.6), Ingredient("pineapple", 5.2, 0.2)), false, false, 91)

      val os = AvroOutputStream.data[Pizza](new File("pizzas.avro"))
      os.write(pepperoni)
      os.write(hawaiian)
      os.close()

      val is = AvroInputStream.data[Pizza](new File("pizzas.avro"))
      val pizzas = is.iterator.toList
      pizzas shouldBe List(pepperoni, hawaiian)
      is.close()
```

Binary support:
```scala

      val pepperoni = Pizza("pepperoni", Seq(Ingredient("pepperoni", 12, 4.4), Ingredient("onions", 1, 0.4)), false, false, 98)

      val os = AvroOutputStream.binary[Pizza](new File("pizzas.avro.binary"))
      os.write(pepperoni)
      os.close()

      val is = AvroInputStream.binary[Pizza](new File("pizzas.avro.binary"))
      val pizzas = is.iterator.toList
      pizzas shouldBe List(pepperoni)
      is.close()
```

Json Support:
```scala
      val pepperoni = Pizza("pepperoni", Seq(Ingredient("pepperoni", 12, 4.4), Ingredient("onions", 1, 0.4)), false, false, 98)
      val hawaiian = Pizza("hawaiian", Seq(Ingredient("ham", 1.5, 5.6), Ingredient("pineapple", 5.2, 0.2)), false, false, 91)

      val os = AvroOutputStream.json[Pizza](new File("pizzas.json"))
      os.write(pepperoni)
      os.write(hawaiian)
      os.close()

      val is = AvroInputStream.json[Pizza](new File("pizzas.json"))
      val pizzas = is.iterator.toList
      pizzas shouldBe List(pepperoni, hawaiian)
      is.close()
```

All the same except for the factory methods you now invoke.
