### ISSUE TITLE
Is there a way to generate hierarchy in the generated classes?

### ISSUE THREAD

**Issue by jazzyguitar** [sksamuel/avro4s#533]
I'm trying to split large schema that we have so that the common fields will sit in a parent schema and specific fields for each class will sit in their schema. does avro4s can generate classes that "extends"?

**Comment by andreas-schroeder** [comment]
Hi @jazzyguitar, not out of the box, no. avro4s works mainly with case classes, and provides you with automatic encoder / decoder generation for that. In theory, you could of course implement your own custom encoder / decoder, but I'd expect that the lines of code saved through inheritance wouldn't amortize the effort.

Also, if you wanted to split a large Avro schema into smaller ones, you need to reflect that in the data structure as well, since that would be used to derive the Avro schema from, and use composition - that's how you would mimic inheritance with Avro anyway.
