### ISSUE TITLE
Implement for Dotty/Scala3 

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/avro4s#563]
@mberndt123 @andreas-schroeder 

In this branch: https://github.com/sksamuel/avro4s/tree/feature/dotty/avro4s-core/src

I have a very very basic starting point for Avro4s for Dotty. I can encode/decode case classes with primitive fields. I can generate schemas for those too.

Now, I would like to get your feedback before proceeding. The implementation doesn't matter so much, as it's just a starting point that will change considerably. I'm more soliciting feedback on the typeclass structures.

`SchemaFor` is as before.
`AvroValue` wraps all types into values compatible with the Java Avro library.
`Encoder` accepts a Scala value and a schema and provides an `AvroValue | AvroError`.
`Decoder` accepts an `AvroValue` and a schema and provides a Scala value  | AvroError.

`map` and `contramap` implemented as you'd expect.

**Comment by mberndt123** [comment]
Hey @sksamuel,

I think I need to apologize to you, because I came up with this whole idea of an `AvroValue`, and I've come to the conclusion that it's probably a bad idea for two reasons:

1. It doesn't match how Avro works. The idea behind `AvroValue` was that there is only a finite number of types that Avro will stick into a `GenericRecord`. But this isn't actually the case, because you can call `addLogicalTypeConversion` on the `GenericData` object and Avro will decode Avro data into arbitrary things. Now we can just ignore this and pretend it doesn't exist, but then we need to duplicate stuff in Avro4s that the Java implementation already does, namely things like `BigDecimal` decoding. I would prefer to leverage that. 
1. Performance. The Decoder knows what it expects. If it's e. g. an `Int` decoder, it only needs to check if the value to be decoded is an `Int` and error out for everything else. No matter how you optimize the `unsafeFromAny` method, it doesn't know what the Decoder wants and can thus never be as fast.

When I first saw the `decode` signature with `Any`, I had this visceral reaction of “eeeewwww, `Any`!”, but I think I was just wrong about that.

Regarding the `Decoder` interface, I think I wouldn't use `T | AvroError` as a return type but stick with a plain old `Either` instead. One reason is that you can't write a `Decoder[AvroError]` if you do things like that. Another reason is that you don't get all the nice functionality of `Either`, like `map`, `flatMap`.
I would also suggest getting rid of the `Schema`, parameter, because if we leverage the [`Conversion`](http://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/Conversion.html) stuff, we're probably not going to need it.
Another idea would be to make the `Decoder` trait sealed. If you make the API sufficiently compositional, every decoder for a complex type can be written by combining some finite set of built-in decoders for Int, Double, String, etc..
We would have to come up with some way to deal with the `Conversion` stuff, e. g. `case class ConversionDecoder[T](conv: Conversion[T]) extends Decoder[T]`. This decoder wouldn't do any decoding itself but just let Avro sort it out with the `Conversion` and then cast the value to `T`. Note that this implies we cannot make `Decoder` a Monad, because the `Conversion`s need to be added before we even start decoding, so we need a way to get all the needed `Conversion`s from a decoder before we start decoding. We could make it an Applicative functor by adding a `zip` method, or, if we need a more powerful abstraction, a [selective applicative functor](https://dl.acm.org/ft_gateway.cfm?id=3341694). Another obvious addition would be to make it an `Alternative`, i. e. add a `orElse` method.

I haven't thought too much about the `Encoder` typeclass, but perhaps we can draw some inspiration from category theory. `Decoder` is a `Functor`, and `Encoder` is a `Contravariant`, which is the categorical dual of a `Functor`. But `Decoder` is also an `Applicative` and an `Alternative`, so maybe `Encoder` is an instance of those typeclasses' duals, which would be `Divisible` and `Decidable`. There's a [hilarious talk](https://youtu.be/IJ_bVVsQhvc) about those if you're interested.

**Comment by sksamuel** [comment]
A lot for me to digest here. I appreciate the detailed write up. Let me go through things one by one in a random order.

* You've convinced me immediately that Either is better. I will update the branch.
* Conversions work when you're using Avro's readers/writers to get your record instances. I guess if you were getting them elsewhere (does kafka's serializer just do it directly?) they might be bypassed so we might need to call them. Something to think about. Avro has a fixed number of types it will support when writing out as binrary, and the logical types just map to one of those 10/15 types, whatever the number is. If we're always going through Avro's readers/writers then you could be getting back any type. I suppose Any is the only possible type signature then.
* Your performance point adds credence to this. One reason I didn't merge the AvroValue thing I had done on that earlier PR was  because the giant match statement to convert was really slow.
* I'm not sure if we need schema or not in decoder, if everything you need to work with is present in the value. I think it's needed in the encoder because the schema can affect what type is output (eg Fixed vs Utf8 for strings). I guess if after building out the rest of the typeclass implementations not a single one is using it, it can just be nuked away then. The good thing about forced re-writes is we can break anything we need to.
* I'm not sure I agree with sealing the typeclasses. From a purist point of view it might have some merit. What's the benefit from a pragmatic point of view? You could convince me though :)
* I'm not familiar with [Alternative](https://typelevel.org/cats/typeclasses/alternative.html) and the docs don't help me. Can you explain that without the Haskell jargon that Cats is using.

**Comment by andreas-schroeder** [comment]
Hey @mberndt123 & @sksamuel , again I am short on time, so leaving here rough ideas:
1. Leaving the logical type converters problem aside, couldn't we just define AvroValue an alias of a type union of the allowed types instead of wrapping them into case classes?
2. Changing Decode return type to Either ias something I would be careful about - mainly for one reason. Looking at how the record decoding works, we are using the short-circuit behaviour of exceptions when decoding fields. Using Either, we would need to reprogram the semantics exceptions already give us. This is also on the critical path so I would recommend to microbenchmark the impact of this.
3. If Encoder/Decoder would be sealed, we would need to make sure typeclass derivation would work without defining anonymous subclasses of these types (and we would have to declare all subtypes in one file...). I think that the main value proposition of avro4s is automatic Encoder/Decoder derivation. A compositional API for constructing Encoders/Decoders would be valuable too for cases requiring heavy cusomization that are more tedious to achieve through other means, but I feel that this would be a secondary value proposition. Still, I wouldn't want to take away the option to define fully custom encoders and decoders; that option was what allowed my team to continue to use avro4s 3 even though it has its performance issues. Other clients might want to customize encoders and decoders for very specific and unpredictable reasons; e.g., to introduce metrics for monitoring of certain edge cases. And finally, I don't see the benefit we or clients would have from making the Encoder / Decoder traits sealed. Can you explain what value you see?

**Comment by mberndt123** [comment]
Hey @sksamuel and @andreas-schroeder 

`Alternative` is not complicated. It's just an `Applicative` that has `empty` and `combineK` in addition to `pure` and `ap`. An example is `Option` where `empty` is `None` and `combineK` is Option's `orElse` method. 

```scala
trait Alternative[F[_]] extends Applicative[F[_]] {
  def empty[A]: F[A]
  def (a: F[A]) combineK[A](b: F[A]): F[A]
}
```
If you squint a bit, this looks almost like a Monoid
```scala
trait Monoid[A] {
  def empty: A
  def (a: A) combine(b: A): A
}
```
And the same laws apply: associativity and identity, i. e. `a.orElse(b).orElse(c) === a.orElse(b.orElse(c))`, `a.orElse(empty) === a` and `empty.orElse(a) === a`.

It's possible to make `Decoder` an instance of `Alternative` (if `E` is a `Monoid`, you can write an `Alternative` instance for `Either[E, *]`, and then it's trivial to write one for `Decoder` too), but I've thought about it some more and I'm not convinced that it would be a good idea. The problem is that if you want to adhere to the laws, you need to implement `combineK` in a way that will try to decode everything and retain all the errors rather than just terminating when it hits the first error. The `Selective` typeclass may be better in that regard, but I need to think (and read) about this some more. Unlike `Applicative` and `Alternative` which have been around for many years, `Selective` is a fairly recent idea, and I haven't worked with it yet, so I can't really explain it. You can read the paper I've linked to earlier, and there seem to be [several videos on YouTube](https://www.youtube.com/results?search_query=selective+applicative+functor). 

Regarding the `sealed Decoder`s, the primary benefit would be that the user would never be compelled to implement `decode` himself. This steers users into the right direction when it comes to using the library  – don't implement yourself, compose from smaller pieces. More importantly, users would never be exposed to `Any` – the `decode` method could actually be `private[avro4s]` and only be exposed through type-safe interfaces.

Regarding @andreas-schroeder's remark about short-circuiting, I don't understand really understand it – short-circuiting is  what `Either` does. Assuming you're using it right, that is: `foo.flatMap(bar).flatMap(baz)` won't short-circuit properly like `foo.flatMap(x => bar(x).flatMap(baz))` does.

Regarding efficiency, I my intuition is that the most important aspect would be to keep the schema out of the decoding loop entirely. If a schema is needed at all, it should be considered once when you e. g. start reading a file and then never be looked at again. This makes it necessary to change the signature from `def decode(any: Any, schema: Schema): Either[AvroError, T]` to `def decode(schema: Schema): Any => Either[AvroError, T]`. This way you can call `decode` once initially and then repeatedly call the function that was returned. Of course the idea is to return a different function from `decode` depending on the Schema, and not always the same function that then looks at the schema later on when it starts to actually decode stuff.
Another possibility is to get rid of the Schema entirely. This would make it necessary to find a way to deal with different possible encodings of e. g. Strings (fixed or utf-8). We can write a type that wraps a string (or perhaps use an opaque type alias to avoid overhead) and is parametrized with a number that specifies that string's maximum length. Values of this type would then be encoded using Avro's `fixed` type. This would have the additional advantage that encoding the data would never fail – the type system makes sure that the maximum string length is adhered to. We can take some inspiration from how [refined](https://github.com/fthomas/refined) does it. Surprisingly it doesn't allow size constraints for Strings, but it does for collections, so it should be possible to adapt that.
