### ISSUE TITLE
when com.sksamuel.avro4s.refined._ is in scope, incorrect schema for case classes having fields of type vector of tuples 

### ISSUE THREAD

**Issue by Zhen-hao** [sksamuel/avro4s#577]
```
  import com.sksamuel.avro4s.refined._
  case class VectorOfTuples(name: String, vec: Vector[(Int, Long)])
  println(s"VectorOfTuples schema is ${AvroSchema[VectorOfTuples]}")
```
produces

```
VectorOfTuples schema is {"type":"record","name":"VectorOfTuples","namespace":"com.nt.util.serialization.AvroMappingSpec","fields":[{"name":"name","type":"string"},{"name":"vec","type":{"type":"array","items":"int"}}]}
```

The type for `vec` is obviously wrong.

**Comment by r-glyde** [comment]
I think this might be related to #571 which just had a fix merged from #572. Might be worth trying the latest snapshot version (that I think gets built on PR merges) and seeing if that fixes the problem.

**Comment by Zhen-hao** [comment]
@r-glyde thanks! looking at the content of your PR, it should definitely fix this issue.
I'll try to find time to test this later this week. 
anyone who has tested it can feel free to close this issue

**Comment by Zhen-hao** [comment]
@r-glyde how can I get the snapshot version?

**Comment by r-glyde** [comment]
I think you probably just need a new resolver in sbt to access the snapshots. From [here](https://www.scala-sbt.org/1.x/docs/Resolvers.html#Resolvers) something like:
```scala
resolvers += Resolver.sonatypeRepo("snapshots")
```
should work I think. And then using the latest snapshot version from the badge at the top of the readme (although when I followed the link for that it looked like `4.1.0.31-SNAPSHOT` was actually the latest version rather than `4.1.0.1295-SNAPSHOT` which is currently in the badge so I'm not sure exactly how those are worked out).

**Comment by Zhen-hao** [comment]
@r-glyde it works with `4.1.0.31-SNAPSHOT`

The schema output is 
```
{"type":"record","name":"VectorOfTuples","namespace":"com.nt.util.serialization.AvroMappingSpec","fields":[{"name":"name","type":"string"},{"name":"vec","type":{"type":"array","items":{"type":"record","name":"Tuple2","namespace":"scala","fields":[{"name":"_1","type":"int"},{"name":"_2","type":"long"}]}}}]}
```

Thank you for the fix!
