### ISSUE TITLE
Spark 3.x compatibility

### ISSUE THREAD

**Issue by cchantep** [sksamuel/avro4s#621]
Since the [Avro dependency has been updated in may 2019 from 1.8.2](https://github.com/sksamuel/avro4s/commit/126cb23bb2e4046ef0d8eb67f19bb99f5b969d48#diff-539d15a8d5ba9a01a1724604b56cadf6851c57ec68dcf75a5073b6255d182de7R10) (the version provided by Spark 3.0.x & 3.1.x), avro4s cannot be used in a Spark job without leading to fatal `NoSuchMethodError` (e.g. `java.lang.NoSuchMethodError: org.apache.avro.Schema$Field.<init>(Ljava/lang/String;Lorg/apache/avro/Schema;Ljava/lang/String;)V`).

Latest avro4s version with compatible dependency is [2.0.4](https://search.maven.org/artifact/com.sksamuel.avro4s/avro4s-core_2.12/2.0.4/jar).

**Comment by sksamuel** [comment]
1.8.2 was released in May 2017, nearly 4 years ago.
Are Spark not going to upgrade their dependencies?

**Comment by cchantep** [comment]
> 1.8.2 was released in May 2017, nearly 4 years ago.
> Are Spark not going to upgrade their dependencies?

You can ask then, but as avro & spark are quite often part of the same ecosystem, this incompatibility is not very nice.

**Comment by sksamuel** [comment]
Yeah I agree that's not ideal.

**Comment by cchantep** [comment]
Still up-to-date

**Comment by kostaskougios** [comment]
Hi, I am having a data compatibility issue between spark 3.1.1 and avro4s 4.0.9, maybe related to the above.
java.sql.Timestamp written with spark is not read correctly by avro4s. Looking at the values, timestamp has a long with the time in millis. Avro4s reads 1000x that value resulting in a corrupted date. I.e. if spark value was 10, avro4s reads it 10000. I understand that this is probably due to the avro lib incompatibility but is there something that can be done?

Note spark reads ok avro4s timestamp values.

**Comment by cchantep** [comment]
up

**Comment by cchantep** [comment]
I think this has far more priority than moving forward Scala3 (which won't be supported by framework like Spark until years).

**Comment by cchantep** [comment]
up

**Comment by cchantep** [comment]
Up

**Comment by cchantep** [comment]
Is there anything planned. That's quite blocker for any Spark project.

**Comment by cchantep** [comment]
Up

**Comment by cchantep** [comment]
Up

**Comment by cchantep** [comment]
up

**Comment by cchantep** [comment]
Up
