### ISSUE TITLE
Can't use custom type mappings for value classes

### ISSUE THREAD

**Issue by vlovgr** [sksamuel/avro4s#75]
It seems like custom `ToValue` and `FromValue` instances for value classes are not being picked up by the `ToRecord` macro.

Example:
```
import java.io.ByteArrayOutputStream

import com.sksamuel.avro4s._
import org.apache.avro.Schema
import org.apache.avro.Schema.Field

object Main extends App {
  final case class Item(valueString: String) extends AnyVal {
    def value: Int = valueString.toInt
  }

  object Item {
    implicit object ItemToSchema extends ToSchema[Item] {
      override val schema: Schema = ToSchema.IntToSchema()
    }

    implicit object ItemToValue extends ToValue[Item] {
      override def apply(item: Item): Int = item.value
    }

    implicit object ItemFromValue extends FromValue[Item] {
      override def apply(value: Any, field: Field): Item =
        Item.apply(FromValue.IntFromValue(value, field).toString)
    }
  }

  final case class Group(item: Item)

  val group = Group(Item("123"))

  println(ToRecord[Group].apply(group))

  val baos = new ByteArrayOutputStream()
  val output = AvroOutputStream.json[Group](baos)
  output.write(group)
  output.close()

  println(baos.toString("UTF-8"))
}
```

Gives:
```
{"item": "123"}
[error] (run-main-2c) java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:117)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:153)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:143)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:105)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:60)
	at com.sksamuel.avro4s.AvroJsonOutputStream.write(AvroOutputStream.scala:83)
...
```

(The `ToSchema` is picked up, but the `ToValue` and `FromValue` are not.)

Making `Item` a normal case class yields the expected results:
```
{"item": 123}
{"item":123}
```

**Comment by rrodseth** [comment]
Any progress on this?

**Comment by sksamuel** [comment]
No progress from me. I'm happy to take a PR on this.

**Comment by marcin-rzeznicki** [comment]
I added support for automatic (macro-based) generation of `ToSchema` and friends to my lib. https://github.com/theiterators/kebs/tree/master/avro/src/main/scala/pl/iterators/kebs/avro . Would you be interested in adding this to `avro4s`?

**Comment by sksamuel** [comment]
If you PR to update `ToRecord` so that it accepts custom `ToValue` `FromValue` that would be accepted with thanks.

**Comment by bergmark** [comment]
IIUC automatically generating the schema as kebs does would not resolve this issue since that would reuse the schema for the inner field, is that right?

Our situation is that we have value classes with a private constructor, e.g.:

```scala
final class NonEmptyString private[NonEmptyString](override val toString: String) extends AnyVal
object NonEmptyString {
  def apply(s: String): Option[String] = if (s != "") None else Some(new NonEmptyString(s))
}
```

This gives a compilation error `constructor NonEmptyString in class NonEmptyString cannot be accessed in <$anon: com.sksamuel.avro4s.FromRecord[CaseClass]>` because the constructor is used without checking if it's public in https://github.com/sksamuel/avro4s/blob/master/avro4s-macros/src/main/scala/com/sksamuel/avro4s/FromRecord.scala#L310

Adding a `sig.typeSymbol.asClass.primaryConstructor.isPublic` check resolves the compilation error and should work for my example but it does not resolve @vlovgr's issue. So I'm not suggesting to include this check by itself since I prefer a compilation error to runtime issues.

Possible workarounds are dropping the `AnyVal` from the original type or creating a wrapper type that is not a value class.

**Comment by sksamuel** [comment]
This is now supported in 2.0 development branch.
